added intra and inter cosine comparisons (for recommendatins and blen…
viral98/music-recommendations pull request #20
Opened 2022-04-14 22:02 UTC by kshitijnair

…d matrices)

2022-04-14 22:25 UTC, kevintab95 requested changes
Thanks @kshitijnair! Left a couple of comments PTAL.

2022-04-14 22:25 UTC, kevintab95 commented on src/getCosineSimilarities.ts
>    const averageCosineSimilarity = cosineSimilaritiesOfAllReccomendations / 45;
Please double check the denominator here

2022-04-14 22:25 UTC, kevintab95 commented on src/getCosineSimilarities.ts
> +  const averageCosineSimilarity = cosineSimilaritiesOfAllReccomendations / 45;
Ditto: denominator

2022-04-14 22:25 UTC, kevintab95 commented on src/app.ts
> +  console.log(`\nInter-List similarity (Spotify-Generated Blend Playlist) is: ${getInterCosineSimilarities(recomMatrix, blendMatrix).toFixed(5)}`);
Not sure if this is useful, we are comparing the similarity of two different recommendations here (whose seeds were completely different.)

2022-04-14 22:25 UTC, kevintab95 commented on src/app.ts
> +  console.log(`\nInter-List similarity (Spotify-Generated Blend Playlist) is: ${getInterCosineSimilarities(recomMatrix, blendMatrix).toFixed(5)}`);
Perhaps this is a more useful metric?
https://towardsdatascience.com/evaluation-metrics-for-recommender-systems-df56c6611093#:~:text=three%20recommender%20systems.-,Personalization,recommendations.%20An%20example%20will%20best%20illustrate%20how%20personalization%20is%20calculated.,-Example%20list%20of

2022-04-14 23:56 UTC, viral98 commented on .env
> +SPOTIFY_KEY="BQDfd4v8ATYWyJonXgFaA1uq2XsfHmvkNWy1xROYHUdZ-B_49o9fBOam-t3258TuNpMJqnqWbhil0iP9MhtOgeIfcQ-MgEN6f5pXAPf2vRmo4qV0S2gBivZAkVQhyJd6uFBQBKJVuCaMDN-jwzPYpCKiTqCAeUjMOfCnMlg"
Reverrttt

2022-04-15 00:01 UTC, viral98 commented on src/getCosineSimilarities.ts
> +      sizeB = matrixB.length;
What is sizeB used for?

2022-04-15 01:46 UTC, viral98 commented on src/getCosineSimilarities.ts
> +  const averageCosineSimilarity = cosineSimilaritiesOfAllReccomendations / 45;
Count the number of elements you are adding and divide by that valuye

2022-04-16 18:04 UTC, viral98 commented
@kevintab95 @kshitijnair I am merging this one to master, @kshitijnair could you send a follow-up to fix the hardcoded 45 issue? Thanks lads :D

2022-04-16 18:04 UTC, merged